[tool.ruff]
line-length = 88
target-version = "py38"
src = ["setup.py", "siggen"]

[tool.ruff.lint]
# Enable pycodestyle (E), pyflakes (F), and bugbear (B) rules
select = ["E", "F", "B"]
ignore = ["E501"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    py38
    py39
    py310
    py311
    py312
    py39-lint
    py39-norequests

[gh-actions]
python =
    3.8: py38
    3.9: py39, py39-lint, py39-norequests
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
deps = -rrequirements-dev.txt
allowlist_externals = {toxinidir}/bin/run_cmd_tests.sh
commands = 
    pytest
    {toxinidir}/bin/run_cmd_tests.sh

[testenv:py39-lint]
deps = -rrequirements-dev.txt
commands =
    ruff format --check setup.py siggen
    ruff check setup.py siggen

[testenv:py39-norequests]
deps =
install_command = pip install {packages}
allowlist_externals = {toxinidir}/bin/run_cmd_tests.sh
commands =
    {toxinidir}/bin/run_cmd_tests.sh --no-requests
"""
