---
name: CI

on:
  push:
    branches: main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    name: Python ${{ matrix.python-version}}
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install '.[cli,dev]'

      - name: Lint
        run: make lint

      - name: Test
        run: tox

  norequests:
    name: Python 3.9 with no requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run commands with no requests
        run: ./bin/run_cmd_tests.sh --no-requests
