---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.7
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.7

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.9

      - name: Update pip and install tox
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint
        run: make lint

      - name: Test
        run: make test
