name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # actions/checkout@v2.0.0
    - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598

    - name: Set up Python 3.5
      # actions/setup-python@v1.1.1
      uses: actions/setup-python@28a6c1b915d5808acb3da49af7063544ebfbe085
      with:
        python-version: 3.5

    - name: Set up Python 3.6
      uses: actions/setup-python@28a6c1b915d5808acb3da49af7063544ebfbe085
      with:
        python-version: 3.6

    - name: Set up Python 3.7
      uses: actions/setup-python@28a6c1b915d5808acb3da49af7063544ebfbe085
      with:
        python-version: 3.7

    - name: Set up Python 3.8
      uses: actions/setup-python@28a6c1b915d5808acb3da49af7063544ebfbe085
      with:
        python-version: 3.8

    - name: Update pip and install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Tox
      run: tox
